# Generated by Django 5.2.7 on 2026-04-14 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1075_workflowaction_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New chat",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                ("pinned", models.BooleanField(default=False, verbose_name="pinned")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="last message at",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        default="default",
                        max_length=255,
                        verbose_name="agent id",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chats",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat",
                "verbose_name_plural": "chats",
                "ordering": ("-pinned", "-last_message_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("streaming", "Streaming"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="content"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="model",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="run id",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="error code",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="error message",
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="input tokens",
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="output tokens",
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="total tokens",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="documents.chat",
                        verbose_name="chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ChatToolCall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_call_id",
                    models.CharField(max_length=255, verbose_name="tool call id"),
                ),
                (
                    "tool_name",
                    models.CharField(max_length=255, verbose_name="tool name"),
                ),
                (
                    "arguments_text",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="arguments text",
                    ),
                ),
                (
                    "output_text",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="output text",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="documents.chatmessage",
                        verbose_name="message",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat tool call",
                "verbose_name_plural": "chat tool calls",
            },
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat", "created_at"],
                name="documents_c_chat_id_e12e83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["run_id"], name="documents_c_run_id_1ed773_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["status"], name="documents_c_status_1a0253_idx"),
        ),
        migrations.AddConstraint(
            model_name="chattoolcall",
            constraint=models.UniqueConstraint(
                fields=("message", "tool_call_id"),
                name="documents_chattoolcall_message_tool_call_unique",
            ),
        ),
    ]
