# Generated by Django 5.2.7 on 2026-04-16 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1076_chat_chatmessage_chattoolcall_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.IntegerField(
                        choices=[(-1, "Negative"), (1, "Positive")],
                        verbose_name="vote",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_entries",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="documents.chatmessage",
                        verbose_name="message",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback",
                "verbose_name_plural": "feedback",
            },
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.CheckConstraint(
                condition=models.Q(document__isnull=False)
                | models.Q(message__isnull=False),
                name="documents_feedback_has_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                condition=models.Q(message__isnull=False),
                fields=("owner", "message"),
                name="documents_feedback_owner_message_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["owner", "created_at"],
                name="documents_f_owner_i_32e664_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["message", "created_at"],
                name="documents_f_message_1ceee7_idx",
            ),
        ),
    ]
